name: Snyk Container Monitor Demo

on:
  push:
    branches:
      - main

jobs:
  build-and-monitor:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-node-app:communify .

      # Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-node-app:communify

      # Install the Snyk CLI
      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      # Monitor the image with Snyk
      - name: Snyk Container Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk container monitor ${{ secrets.DOCKER_USERNAME }}/demo-node-app:communify
